name: singalong_frontend

packages:
  - apps/**
  - packages/features/**

scripts:
  analyze:
    exec: dart analyze .
  format: 
    name: "format"
    description: "Format dart files using dart fix and import sorter"
    run: | 
      dart fix --dry-run --apply &&
        (dart run import_sorter:main || (dart pub add --dev import_sorter && dart run import_sorter:main))
    exec:
      failFast: true
  format:sort:
    name: "format:sort"
    description: "Sort dart imports using import sorter"
    exec: dart pub add --dev import_sorter && dart run import_sorter:main

  install:
    name: "install"
    description: "Install dart packages on all packages"
    run: dart pub add
    exec:
      concurrency: 1
      failFast: true
  install:apps:
    name: "install:apps"
    description: "Install dart packages for apps packages"
    run: dart pub add
    exec:
      concurrency: 1
      failFast: true
    packageFilters:
      scope: "*_app"
  install:services:
    name: "install:service"
    description: "Install dart packages for service modules. Run with `--no-select` to install all services."
    run: dart pub add
    exec:
      concurrency: 1
      failFast: true
    packageFilters:
      scope: "*_service"
  install:features:
    name: "install:feature"
    description: "Install dart packages for feature modules"
    run: dart pub add
    exec:
      concurrency: 1
      failFast: true
    packageFilters:
      scope: "*_feature"