openai:
  token: "sk-1234567890abcdef1234567890abcdef"
cors:
  allowedOrigins: "http://localhost,http://thursday.local,http://localhost:8085,http://thursday.local:8085"
jwt:
  secret: "abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890"
spring:
  data:
    mongodb:
      port: 27017
      username: karaoke
      password: master
      database: singalong
    auto-index-creation: $MONGO_AUTO_INDEX_CREATION
singalong:
  seeders:
    admin:
      username: "pat"
      passcode: "1234"
    room:
      id: "admin"
      name: "Admin Room"
      passcode: "admin"
socketio:
  hostname: 0.0.0.0
  port: 9092
minio:
  endpoint: "http://localhost:9000"
  accessKey: "karaokedata"
  secretKey: "masterdata"