credentials-file: /etc/cloudflared/credentials.json

ingress:
  - hostname: singalong.fun
    service: http://client:80
  - hostname: api.singalong.fun
    service: http://server:8080
  - hostname: socket.singalong.fun
    service: http://server:9092
  - hostname: storage.singalong.fun
    service: http://minio:9000
  - service: http_status:404