services:
  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "8005:8005"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server
      - minio
    networks:
      - singalong-server
  client:
    image: singalong-client:1.0.0
    build:
      context: client/apps/controller
      dockerfile: Dockerfile
    container_name: singalong-client-container
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - singalong-server

  admin:
    image: singalong-admin:1.0.0
    build:
      context: client/apps/admin
      dockerfile: Dockerfile
    container_name: singalong-admin-container
    ports:
      - "8081:80"
    depends_on:
      - server
    networks:
      - singalong-server

  server:
    image: singalong-server:1.0.0
    build:
      context: server
      dockerfile: Dockerfile
    container_name: server-container
    ports:
      - "8080:8080"
      - "5005:5005" # Debug port
    depends_on:
      - js-service
      - mongodb
      - minio
      - ngrok
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=docker,secrets
      - SPRING_APPLICATION_NAME=singalong-server
      - SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE=$MONGO_DB
      - SPRING_DATA_MONGODB_AUTO_INDEX_CREATION=$MONGO_AUTO_INDEX_CREATION
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    networks:
      - singalong-server

  js-service:
    image: singalong-js:1.0.0
    build:
      context: microservices/js-service
      dockerfile: Dockerfile
    container_name: js-service-container
    ports:
      - "3000:3000"
    networks:
      - singalong-server
    volumes:
      - $SONG_DOWNLOAD_PATH:/app/songs

  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
      MONGO_INITDB_DATABASE: $MONGO_INITDB_DATABASE
      MONGO_DB_USERNAME: $MONGO_DB_USERNAME
      MONGO_DB_PASSWORD: $MONGO_DB_PASSWORD
    volumes:
      - mongodb_data_v6:/data/db
      - ./init-mongo:/docker-entrypoint-initdb.d
    networks:
      - singalong-server
    command: ["--bind_ip", "0.0.0.0"]

  minio:
    image: minio/minio
    container_name: minio-container
    ports:
#      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: $MINIO_ACCESS_KEY
      MINIO_SECRET_KEY: $MINIO_SECRET_KEY
    volumes:
      - $MINIO_DATA_PATH:/data
    command: server /data --console-address ":9001"
    networks:
      - singalong-server

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok-container
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
      - "--config"
      - "/etc/ngrok-auth.yml"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - "4040:4040"
    configs:
      - source: ngrok-auth.yml
        target: /etc/ngrok-auth.yml
    networks:
      - singalong-server

networks:
  singalong-server:
    driver: bridge

volumes:
  mongodb_data:
  mongodb_data_v6:

configs:
  ngrok-auth.yml:
    file: ./ngrok-auth.yml