baseurl:
  js-service: http://js-service:3000
openai:
  local: true
  host: http://host.docker.internal:1234/v1/
  model: "TheBloke/Mistral-7B-Instruct-v0.2-GGUF/mistral-7b-instruct-v0.2.Q4_K_S.gguf"
spring:
  data:
    mongodb:
      host: mongodb
minio:
  endpoint: "http://minio:9000"