name: connectfeatureds
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  shared:
  common:
  connectfeature:

  singalong_api_client:
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
