name: SingalongPlayer
organizationName: Patteruel
bundleIdPrefix: dev.patteruel

settings:
  SWIFT_VERSION: 5.9

targets:
  SingalongPlayer:
    type: application
    platform: [iOS, macOS]
    deploymentTarget:
      iOS: "16.0"
      macOS: "13.0"
    sources:
      - path: Sources
        includes:
          - "**/*.swift"
      - path: SingalongPlayer
        includes:
          - "**/*.swift"
    resources:
      - path: SingalongPlayer/Assets.xcassets
      - path: SingalongPlayer/Preview\ Assets.xcassets
      - path: SingalongPlayer/Info.plist
    info:
      path: SingalongPlayer/Info.plist
      useBaseLocalizationAsUnderscore: true
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: dev.patteruel.singalong.player
      DEVELOPMENT_TEAM: ""
      CODE_SIGN_STYLE: Automatic
      INFOPLIST_FILE: SingalongPlayer/Info.plist
      TARGETED_DEVICE_FAMILY: "1,2"
