baseurl:
  songdownloader: http://localhost:3000
openai:
  local: true
  host: http://localhost:1234/v1/
  model: "TheBloke/Mistral-7B-Instruct-v0.2-GGUF/mistral-7b-instruct-v0.2.Q4_K_S.gguf"
spring:
  data:
    mongodb:
      host: localhost
minio:
  endpoint: "http://localhost:9000"